create database studentdata;
use studentdata;
create table register (rollnumber int,studentname varchar(20));
insert into register values('2','Subbu');
insert into register values('1','Satya');
insert into register values('3','Guru');
insert into register values('4','Anurag');
insert into register values('5','Saurav');
insert into register values('6','Harsha');
insert into register values('7','Indhu');
insert into register values('8','Lucky');
insert into register values('9','Harika');
insert into register values('10','Prathyusha');
insert into register values('11','Vaishnavi');
insert into register values('12','Ishwarya');
insert into register values('13','HimaBindhu');
select * from register;
